package agent

import (
	"bytes"
	"context"
	"fmt"
	"log/slog"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"github.com/maxbeizer/gh-helm/internal/config"
	"github.com/maxbeizer/gh-helm/internal/github"
	"github.com/maxbeizer/gh-helm/internal/notifications"
	"github.com/maxbeizer/gh-helm/internal/sot"
)

type StartOptions struct {
	IssueNumber int
	Repo        string
	Model       string
	DryRun      bool
	Codespace   bool
}

type StartResult struct {
	Session       string       `json:"session"`
	Issue         github.Issue `json:"issue"`
	Plan          github.Plan  `json:"plan"`
	Branch        string       `json:"branch"`
	Pull          PullRequest  `json:"pull_request"`
	DryRun        bool         `json:"dry_run"`
	CodespaceName string       `json:"codespace_name,omitempty"`
	CodespaceURL  string       `json:"codespace_url,omitempty"`
}

type PullRequest struct {
	Number int    `json:"number"`
	URL    string `json:"url"`
}

type ProjectAgent struct{}

func NewProjectAgent() *ProjectAgent {
	return &ProjectAgent{}
}

func (p *ProjectAgent) Start(ctx context.Context, opts StartOptions) (StartResult, error) {
	cfg, err := config.Load("helm.toml")
	if err != nil {
		return StartResult{}, err
	}

	model := opts.Model
	if model == "" {
		model = cfg.Agent.Model
	}
	if model == "" {
		model = "gpt-4o"
	}

	session := strconv.FormatInt(time.Now().Unix(), 10)

	issue, err := github.FetchIssue(ctx, opts.Repo, opts.IssueNumber)
	if err != nil {
		return StartResult{}, err
	}

	if err := github.CommentIssue(ctx, opts.Repo, opts.IssueNumber, fmt.Sprintf("🤖 gh-helm agent starting work (session: `%s`)", session)); err != nil {
		return StartResult{}, err
	}

	if cfg.Project.Board != 0 && cfg.Project.Owner != "" {
		if err := github.MoveIssueToStatus(ctx, cfg.Project.Owner, cfg.Project.Board, issue.NodeID, "In Progress"); err != nil {
			return StartResult{}, err
		}
	}

	sotContent, err := sot.Read(cfg.SourceOfTruth)
	if err != nil {
		return StartResult{}, err
	}

	plan, err := GeneratePlan(ctx, model, issue, sotContent)
	if err != nil {
		return StartResult{}, err
	}

	result := StartResult{
		Session: session,
		Issue:   issue,
		Plan:    plan,
		DryRun:  opts.DryRun,
	}

	if opts.DryRun {
		return result, nil
	}

	branch := fmt.Sprintf("gh-helm/%d-%s", opts.IssueNumber, slugify(issue.Title))
	if err := runCmd(ctx, "git", "checkout", "-b", branch); err != nil {
		return StartResult{}, err
	}

	if err := applyChanges(plan.Files); err != nil {
		return StartResult{}, err
	}

	commitMsg := fmt.Sprintf("%s\n\nCloses #%d\n\nGenerated by gh-helm agent\n\nCo-authored-by: Claudia (AI) <claudia@maxbeizer.com>", issue.Title, opts.IssueNumber)
	if err := stageFiles(ctx, plan.Files); err != nil {
		return StartResult{}, err
	}
	if err := runCmd(ctx, "git", "commit", "-m", commitMsg); err != nil {
		return StartResult{}, err
	}
	if err := runCmd(ctx, "git", "push", "-u", "origin", branch); err != nil {
		return StartResult{}, err
	}

	prTitle := issue.Title
	prBody := fmt.Sprintf("Closes #%d\n\nGenerated by gh-helm agent.", opts.IssueNumber)
	prNumber, prURL, err := createDraftPR(ctx, opts.Repo, prTitle, prBody)
	if err != nil {
		return StartResult{}, err
	}

	if err := github.CommentIssue(ctx, opts.Repo, opts.IssueNumber, fmt.Sprintf("🤖 Draft PR created: #%d", prNumber)); err != nil {
		return StartResult{}, err
	}

	if cfg.Project.Board != 0 && cfg.Project.Owner != "" {
		if err := github.MoveIssueToStatus(ctx, cfg.Project.Owner, cfg.Project.Board, issue.NodeID, "In Review"); err != nil {
			return StartResult{}, err
		}
	}

	notifier := notifications.New(cfg, opts.Repo, opts.IssueNumber)
	if notifier != nil {
		if err := notifier.Notify(ctx, notifications.Message{
			Title:   "🤖 gh-helm: Draft PR ready for review",
			Body:    fmt.Sprintf("PR #%d: %s\nRepo: %s\nIssue: #%d\nAuthor: gh-helm agent (session %s)", prNumber, issue.Title, repoDisplay(opts.Repo), opts.IssueNumber, session),
			Channel: cfg.Notifications.OpsChannel,
			URL:     prURL,
		}); err != nil {
			slog.Warn("notification failed", "error", err)
		}
	}

	result.Branch = branch
	result.Pull = PullRequest{Number: prNumber, URL: prURL}

	if opts.Codespace || cfg.Codespace.Enabled {
		machine := cfg.Codespace.Machine
		if machine == "" {
			machine = "basicLinux32gb"
		}
		idleTimeout := cfg.Codespace.IdleTimeout
		if idleTimeout == "" {
			idleTimeout = "30m"
		}

		csName, csURL, err := CreateCodespace(ctx, CodespaceOpts{
			Repo:        opts.Repo,
			Branch:      branch,
			Machine:     machine,
			IdleTimeout: idleTimeout,
		})
		if err != nil {
			slog.Warn("codespace creation failed", "error", err)
		} else {
			if err := WaitForReady(ctx, csName, 20*time.Minute); err != nil {
				slog.Warn("codespace not ready", "error", err, "name", csName)
			} else {
				result.CodespaceName = csName
				result.CodespaceURL = csURL
			}
		}

		if notifier != nil && result.CodespaceURL != "" {
			if err := notifier.Notify(ctx, notifications.Message{
				Title:   "💻 Codespace ready for review",
				Body:    fmt.Sprintf("PR #%d: %s\nCodespace: %s\nBranch: %s", prNumber, issue.Title, result.CodespaceURL, branch),
				Channel: cfg.Notifications.OpsChannel,
				URL:     result.CodespaceURL,
			}); err != nil {
				slog.Warn("codespace notification failed", "error", err)
			}
		}
	}

	if err := writeStatus(session, issue, result.Pull); err != nil {
		return StartResult{}, err
	}

	return result, nil
}

func applyChanges(files []github.FileChange) error {
	for _, file := range files {
		if file.Path == "" {
			continue
		}
		if err := os.MkdirAll(filepath.Dir(file.Path), 0o755); err != nil {
			return fmt.Errorf("create directory for %s: %w", file.Path, err)
		}
		if err := os.WriteFile(file.Path, []byte(file.Content), 0o644); err != nil {
			return fmt.Errorf("write file %s: %w", file.Path, err)
		}
	}
	return nil
}

func createDraftPR(ctx context.Context, repo, title, body string) (int, string, error) {
	args := []string{"pr", "create", "--draft", "--title", title, "--body", body}
	if repo != "" {
		args = append(args, "--repo", repo)
	}
	slog.Debug("creating draft PR", "title", title, "repo", repo)
	out, err := github.RunWith(ctx, args...)
	if err != nil {
		return 0, "", fmt.Errorf("create draft PR: %w", err)
	}

	// gh pr create outputs the PR URL to stdout (no --json support).
	prURL := string(bytes.TrimSpace(out))
	slog.Debug("draft PR created", "url", prURL)

	// Extract PR number from URL: .../pull/123
	parts := strings.Split(prURL, "/")
	prNumber := 0
	for i, part := range parts {
		if part == "pull" && i+1 < len(parts) {
			fmt.Sscanf(parts[i+1], "%d", &prNumber)
		}
	}
	if prNumber == 0 {
		slog.Warn("could not parse PR number from URL", "url", prURL)
	}
	return prNumber, prURL, nil
}

// RunGitFunc is the function used to execute git CLI commands.
// Override in tests to provide mock responses.
var RunGitFunc = defaultRunGit

func defaultRunGit(ctx context.Context, args ...string) error {
	cmd := exec.CommandContext(ctx, "git", args...)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

func runCmd(ctx context.Context, name string, args ...string) error {
	return RunGitFunc(ctx, args...)
}

func slugify(input string) string {
	input = strings.ToLower(input)
	var b strings.Builder
	lastDash := false
	for _, r := range input {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') {
			b.WriteRune(r)
			lastDash = false
			continue
		}
		if !lastDash {
			b.WriteRune('-')
			lastDash = true
		}
	}
	result := strings.Trim(b.String(), "-")
	if len(result) > 40 {
		result = result[:40]
	}
	if result == "" {
		return "issue"
	}
	return result
}

func repoDisplay(repo string) string {
	if repo != "" {
		return repo
	}
	return "current repo"
}

// stageFiles adds only the specific files from the plan to the git index,
// instead of staging everything with "git add .".
func stageFiles(ctx context.Context, files []github.FileChange) error {
	paths := make([]string, 0, len(files))
	for _, f := range files {
		if f.Path != "" {
			paths = append(paths, f.Path)
		}
	}
	if len(paths) == 0 {
		return nil
	}
	args := append([]string{"add", "--"}, paths...)
	return RunGitFunc(ctx, args...)
}
